// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4VCeqakkE-rG0tjZ3dcOx2mRSysUWYPw',
    appId: '1:557838008642:web:ec6719827301689d0f08db',
    messagingSenderId: '557838008642',
    projectId: 'taskmanagerapp-cac35',
    authDomain: 'taskmanagerapp-cac35.firebaseapp.com',
    storageBucket: 'taskmanagerapp-cac35.firebasestorage.app',
    measurementId: 'G-51E32J8HRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94pawtlkDPhNSyjk2wWSbr_PnHzZasA8',
    appId: '1:557838008642:android:e263950a7d43ae8e0f08db',
    messagingSenderId: '557838008642',
    projectId: 'taskmanagerapp-cac35',
    storageBucket: 'taskmanagerapp-cac35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8Kj_p0zW8h-dl0FbuA7jsvnLHsnjw38',
    appId: '1:557838008642:ios:9ba448199c7dcd1d0f08db',
    messagingSenderId: '557838008642',
    projectId: 'taskmanagerapp-cac35',
    storageBucket: 'taskmanagerapp-cac35.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx8Kj_p0zW8h-dl0FbuA7jsvnLHsnjw38',
    appId: '1:557838008642:ios:9ba448199c7dcd1d0f08db',
    messagingSenderId: '557838008642',
    projectId: 'taskmanagerapp-cac35',
    storageBucket: 'taskmanagerapp-cac35.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4VCeqakkE-rG0tjZ3dcOx2mRSysUWYPw',
    appId: '1:557838008642:web:5304301ab40edbd50f08db',
    messagingSenderId: '557838008642',
    projectId: 'taskmanagerapp-cac35',
    authDomain: 'taskmanagerapp-cac35.firebaseapp.com',
    storageBucket: 'taskmanagerapp-cac35.firebasestorage.app',
    measurementId: 'G-W4E7ZGCVN4',
  );

}